### ISSUE TITLE
All projects on org map experiment

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#1422] opened 2015-04-08 10:34 UTC
We should investigate how expensive it is to add all projects on the organisation page

**Comment by kardan** [comment] 2015-04-08 10:36
Think about to limit the data that is needed!

**Comment by lauraroverts** [comment] 2015-04-22 09:36
If the experiment fails, please add an explanation to the map that says only the 10 projects/updates visible at this page are visible. Otherwise it's not clear to people why they only see a selection of pins

**Comment by kardan** [comment] 2015-07-08 08:46
Related https://github.com/akvo/akvo-rsr/issues/1580

**Comment by lauraroverts** [comment] 2015-09-16 12:47
Duplicate of #1288

**Closed by lauraroverts** 2015-09-16 12:47 UTC
Labels: Backlog, Type: Maps
