### ISSUE TITLE
Navbar wraps on certain RSR pages

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#1796] opened 2015-09-08 11:06 UTC
When the Google translate menu is visible the navbar sometimes wraps.

See:
http://programmes.akvoapp.org/en/projects/
http://rsr.akvo.org/en/projects/

Compare with:
http://iicd.akvoapp.org/en/myrsr/

![screen shot 2015-09-08 at 12 51 55](https://cloud.githubusercontent.com/assets/31837/9733317/7efa0d8a-562a-11e5-854a-90a749616e06.png)

**Comment by gabemart** [comment] 2015-09-16 10:44
This is currently the intended behaviour. The navbar isn't actually wrapping to a new line, it just has padding such that if/when the user selects a menu in the google translate menu, there is space for the translate bar to appear without overlapping the page content.

E.g. http://gfycat.com/HardImperturbableAdouri

One alternative is to only activate the padding when the user clicks the translate element to bring up the menu of language choices. This means the padding isn't present by default, but it also means that the menu will "jump" down as soon as the user activates it (before they choose a language). This is poor UX.

The ideal would be to only activate the padding once the user has chosen a language from the menu, but the translate menu is in a separate iframe so this is not possible using a regular click listener. It may be possible using the API, but this would be considerably more complex.

Three ways forward:

1) Leave it as is (padding is a bit ugly, but the UX is clear)

2) Only activate the padding when the menu button is first clicked (Hide the padding most of the time, but menu will jump position when activated - poorer UX)

3) Investigate the possiblity of using a the API to only show the padding once a language has been chosen (time consuming, may not be possible)

**Comment by gabemart** [comment] 2015-09-16 15:29
@lauraroverts @KasperBrandt any thoughts re: above?

**Comment by KasperBrandt** [comment] 2015-09-17 06:58
@gabemart I actually think the 2nd option is quite good. As I understand it, we'll remove the padding to begin with, but add an onClick to the Translate widget, right?

I don't the Translate bar is used all that often, so in most cases this will end up with a good result. The only thing is that when someone activates the widget and doesn't choose a language or removes the Google Translate bar again, then it'll look as it currently does. Maybe we can even put an additional onClick on the 'cross' icon of the translate bar to set the padding back?

Does that make sense?

**Comment by gabemart** [comment] 2015-09-17 07:13
@KasperBrandt 

>As I understand it, we'll remove the padding to begin with, but add an onClick to the Translate widget, right?

Yep, this is correct

>Maybe we can even put an additional onClick on the 'cross' icon of the translate bar to set the padding back?

This is not possible as the "cross" icon is within the google iframe, so browser security will not let us capture click events. I believe we can capture click events for the translate widget itself because the parent element is in our DOM and is the same size as the iframe contents.

I'll try approach no. 2 and post the results here.

**Comment by gabemart** [comment] 2015-09-17 07:29
Approach 2 looks like this:

http://gfycat.com/RawEminentAustraliancurlew

You can see the navbar padding is applied as soon as the widget is clicked, so rather than the language menu appearing below the widget, it covers it.

It's not too disconcerting though, and if as you say the menu is not used very often, I agree this may be the best option

**Comment by KasperBrandt** [comment] 2015-09-17 07:53
Yeah, I think this looks good :+1:

**Comment by gabemart** [comment] 2015-09-17 10:13
#Test Plan

1) Open an "Akvo Pages" instance of RSR

2) Verify that there is not excess padding above the navbar, as in the screen shot from @kardan 

3) Click the translation widget to bring up the language menu

4) Verify the padding appears

5) Verify you can select a language from the menu

6) Verify the translate bar that appears at the top of the page fits into the padding provided

**Comment by KasperBrandt** [comment] 2015-09-17 12:32
Fixed in #1813

**Closed by KasperBrandt** 2015-09-17 12:32 UTC
Labels: Backlog, Needs Review, Priority 1, Type: UX Required
