### ISSUE TITLE
Bullet points 'break' Project Summary

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2403] opened 2016-10-11 15:38 UTC
Using \* for bullet points in 'Summary of project plan' field causes this section to collapse in the front end.

Steps to reproduce the bug:
1. Go to Project editor and fill in 'Summary of project plan' field in the 04 - Project descriptions section. Use \* for bullet points, e.g.: 
* The group will document successes of these irrigation technologies
2. Save and go to RSR front end 'Summary tab'. This is how it looks

<img width="1211" alt="screen shot 2016-10-11 at 17 35 24" src="https://cloud.githubusercontent.com/assets/21127166/19277210/41fb32d0-8fd9-11e6-877d-c9caa33df32d.png">
3. Click on 'Read more' - the entire section with summary suddenly disappears and it looks like this:

<img width="1218" alt="screen shot 2016-10-11 at 17 34 20" src="https://cloud.githubusercontent.com/assets/21127166/19277259/600a7100-8fd9-11e6-9019-51eced84e6b2.png">

Note that \* for bullet points is used in other Project Editor fields without any troubles so far.

**Comment by punchagan** [comment] 2016-11-29 08:59
Unable to reproduce this with the given information.  Was there specific text that triggered this?

**Comment by nadiagorchakova** [comment] 2016-11-29 14:12
Hi @punchagan 
I could replicate it again - see this project http://rsr.test.akvo.org/en/project/5277/
I added a couple of * to Project Description section in Editor and now the bug pops up again.

**Comment by punchagan** [comment] 2016-11-30 06:45
Thanks! This should be helpful, @nadiagorchakova

**Comment by punchagan** [comment] 2016-12-27 11:51
Closed in #2471

**Closed by punchagan** 2016-12-27 11:51 UTC
Labels: Bug, In Progress, Priority: Low, Type: Project editor
