### ISSUE TITLE
MyRSR search malfunction

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1777] opened 2015-08-27 12:24 UTC
## Test plan
1. Go to the User Management page
2. Search for an organisation
3. All users of the organisation should be returned (if the user has permission to view the user's employment)

## Issue description
In MyRSR user management it is not clear how the searchbox is searching for. Does it provide results for email address? Or for email + first name + last name etc? Is it searching for results at the first page? Or at all pages? 

If I search for 'Cordaid' it gives me 5 users, while there are certainly more users. 

If I search for 'Akvo' it tells me there are 23 users. At the first page I see 10 Akvo users. When I click through to the next page, it seems that the search selection Akvo has disappeared and I see all 227 pages of users again.

**Comment by KasperBrandt** [comment] 2015-09-16 14:17
I'll check this out to be sure, but from the top of my head the MyRSR user management search for email, first name and last name.

This was fixed in the last release (see #1560)

```If I search for 'Akvo' it tells me there are 23 users. At the first page I see 10 Akvo users. When I click through to the next page, it seems that the search selection Akvo has disappeared and I see all 227 pages of users again.```

**Comment by KasperBrandt** [comment] 2015-09-29 10:57
@lauraroverts Not sure what to do with this one. It searches for first name, last name and email address and everything seems to work as intended (probably also due to the fixes in #1560).

**Comment by lauraroverts** [comment] 2015-09-29 11:17
This is solved indeed: If I search for 'Akvo' it tells me there are 23 users. At the first page I see 10 Akvo users. When I click through to the next page, it seems that the search selection Akvo has disappeared and I see all 227 pages of users again.

But still, when I search for Cordaid it only gives me 5 names. It makes sense to also make it possible to search for organisation. Now it doesn't.

**Comment by KasperBrandt** [comment] 2015-09-29 11:30
Ah, yeah.. We can add that easily.

**Closed** 2015-10-05 07:06 UTC
Labels: Needs Review, Priority 1, Type: MyRSR
