### ISSUE TITLE
Translate feature for project content

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1610] opened 2015-06-04 09:43 UTC
A translate feature for Akvo Pages is needed to translate all static project information. Like what was possible in RSR 2.0. 

This feature is a very powerful for demos and sales. Several partners have been requesting getting this back in place, like the Dutch embassy in Mozambique.  

![untitled](https://cloud.githubusercontent.com/assets/4179989/7981244/ebcacee0-0aad-11e5-831e-dc56d31318f8.png)

**Comment by KasperBrandt** [comment] 2015-06-23 07:06
Duplicate of #1617

**Closed by KasperBrandt** 2015-06-23 07:06 UTC
