### ISSUE TITLE
Search in EUTF akvo site

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2526] opened 2017-02-06 15:18 UTC
Partner team had a training and workshop with EUTF last week and discovered that search terms in EUTF akvo site returned unrelated results.

Search for tombouctou shows up a project of SNV in EUTF akvo page, which is confusing for the partner as they expect to see their own projects only on their akvo site. 

<img width="1070" alt="screen shot 2017-02-06 at 15 56 41" src="https://cloud.githubusercontent.com/assets/21127166/22652066/45bdf606-ec85-11e6-9c05-25d421b329c1.png">

What the partner expects is to see just projects where they are one of the participating partners. 
If the search does not match any of their projects, it should then not return anything.

**Comment by punchagan** [comment] 2017-02-21 11:42
Duplicate of https://github.com/akvo/akvo-rsr/issues/1853

**Closed** 2017-03-09 11:52 UTC
Labels: Bug, EUTF, Needs Review
