### ISSUE TITLE
Introduce simple disaggregation of quantitative indicators to the Project Editor 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2769] opened 2017-07-17 15:51 UTC
Similar to introducing qualitative indicators to the Project Editor, disaggregation of indicators needs to be introduced to the Project Editor so that when a Partner is creating a new Results Framework they can add disaggregated Quantitative indicators.

As an initial example of the layout changes and requirements in the Project Editor, we can build off the design already provided for Qualitative indicators: 

<img width="899" alt="screen shot 2017-07-17 at 15 30 27" src="https://user-images.githubusercontent.com/26227538/28276777-35656354-6b18-11e7-84d1-2af7b330b416.png">

**Comment by punchagan** [comment] 2017-09-01 09:33
Duplicate of #2778

**Closed by punchagan** 2017-09-01 09:33 UTC
Labels: Type: Results framework
