### ISSUE TITLE
Qualitative indicators: database (module) for tags/themes for qualitative indicators 

### ISSUE THREAD

**Issue by AkvoAnt** [akvo/akvo-rsr#2763] opened 2017-07-17 09:05 UTC
Create a small database of the themes/tags assigned to qualitative indicators assigned by a Partner to enable easy queries for custom RSR reports.

**Comment by AkvoAnt** [comment] 2017-07-19 09:52
Extend the RSR data model to support qualitative indicators.

**Comment by punchagan** [comment] 2017-09-21 06:59
Duplicate of https://github.com/akvo/akvo-rsr/issues/2772

**Closed by punchagan** 2017-09-21 06:59 UTC
Labels: Type: Project editor, Type: Reports, Type: Results framework
