### ISSUE TITLE
MyRSR User management search function

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1638] opened 2015-07-01 09:41 UTC
When I log in to http://rsr.akvo.org/en/myrsr/user_management/ and search for 'Akvo' I first get 2 pages  with users. 

![screen shot 2015-07-01 at 11 38 48](https://cloud.githubusercontent.com/assets/4179989/8451769/ff54ee58-1fe5-11e5-9541-b68226405adc.png)

If I go to the next page, by clicking on the '2' a the bottom, it looks like I see all users again, meaning that the filtering for Akvo has disappeared. I now have 221 pages of users. 

![screen shot 2015-07-01 at 11 40 46](https://cloud.githubusercontent.com/assets/4179989/8451774/0bcfc9aa-1fe6-11e5-9f31-80d3aa31cfd1.png)

**Comment by KasperBrandt** [comment] 2015-07-13 07:40
Duplicate of #1560

**Closed by KasperBrandt** 2015-07-13 07:40 UTC
Labels: Bug
