### ISSUE TITLE
Mandatory fields in Project Focus (My RSR Project Editor)

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-rsr#2351] opened 2016-09-01 11:22 UTC
I encountered the following issue in RSR Test env:

1. Fields 'Policy Marker' and 'Policy Marker Significance' fields are not marked as mandatory until you fill them in.
2. Even after you fill in all mandatory fields, the progress bar for the section stays yellow.

This is true when IATI or DGIS standard was checked in the Project settings.

![screen shot 2016-09-01 at 12 26 55](https://cloud.githubusercontent.com/assets/21127166/18164497/70001a6e-7040-11e6-998f-5240143a477c.png)

Please review. Thanks!

**Comment by nadiagorchakova** [comment] 2016-09-01 11:49
Same thing in RSR UAT env.
You can have a look at these (unpublished) projects:
RSR Test: http://rsr.test.akvo.org/en/myrsr/project_editor/4521/
RSR UAT: http://rsr.uat.akvo.org/en/myrsr/project_editor/4005/

**Comment by nadiagorchakova** [comment] 2016-09-02 09:46
Annabelle found same issue in RSR Live (Watershed)
http://rsr.akvo.org/en/myrsr/project_editor/4367/

**Comment by zzgvh** [comment] 2016-09-02 13:21
Looking both [here](http://iatistandard.org/202/activity-standard/overview/classifications/) and [here](http://iatistandard.org/202/rulesets/standard-ruleset/) I cannot find that Policy marker should be mandatory. Sector seems to be the only classification that's required. But I've only done a quick read. Or do we have special rule sets that go above the IATI requirements?

**Comment by nadiagorchakova** [comment] 2016-09-02 15:20
Gabriel, you're right! Geert has just changed the settings in http://rsr.test.akvo.org/en/admin/, so now only sector is mandatory. The completion bar is yellow, not matter how many fields you enter though.

**Comment by gabemart** [comment] 2016-09-05 14:51
After having a look, I agree with theory of @zzgvh that this behaviour is caused by `rsr_policymarker.policy` and `rsr_policymarker.significance` being set to "read only" in the admin interface

![image](https://cloud.githubusercontent.com/assets/2589977/18251091/ff0c6e24-737e-11e6-8af5-f450fbf411d9.png)

This status is not implemented in the project editor, or in the `project_editor.py` [template tag](https://github.com/akvo/akvo-rsr/blob/develop/akvo/rsr/templatetags/project_editor.py#L213). `mandatory_or_hidden` only checks for `validation_action` values of "1" or "2", but "readonly" sets a validation action of "3". 

If we wanted to implement this, we would have to edit `mandatory_or_hidden` to add something like a "readonly-{0}" class when the action is 3, and then edit the project editor to give elements with that class a `readonly` html attribute of "true". We could base this on [`markMandatoryFields`](https://github.com/akvo/akvo-rsr/blob/15025bd3645fed420b9dc0602aa5259c0fedfc06/akvo/rsr/static/scripts-src/project-editor.jsx#L2227) which works in a very similar way.

If we don't want to implement this, we just need to disable "readonly" as an option in the django admin

**Comment by zzgvh** [comment] 2016-09-19 12:26
A note for the deployment of this fix. Check that there are no validations set to Read-only. If there are any they should be removed before deploying, as they will break the admin page for project editor validation sets.

**Comment by zzgvh** [comment] 2016-09-22 14:18
Fixed in https://github.com/akvo/akvo-rsr/pull/2357

**Closed by zzgvh** 2016-09-22 14:18 UTC
Labels: In Progress, Priority: High, Type: MyRSR
