### ISSUE TITLE
Cordaid IATI import fix (estimate 6)

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-rsr#2429] opened 2016-11-07 11:30 UTC
Cordaid has requested that we include the previously removed adding of Sponsor partners to represent internal divisions of Cordaid when doing the IATI import for them.

This looks like an easy rollback of this commit: https://github.com/akvo/akvo-rsr/commit/e8cd56aadcfea4b21c06a8ebc81cfd9204063aaf.

However @punchagan has spotted that there are new IDs for the iati-activity@akvo:business-unit-id attribute which is the way we map the Cordaid divisions to RSR organisations.

We need to understand what the new IDs represent before we can move ahead with this change, and consider if this should be fixed or not depending on how much the new IDs complicate things.

**Comment by nadiagorchakova** [comment] 2017-01-19 09:57
The issue is moved to the next milestone because Cordaid has not renewed their contract with Akvo yet. Will wait with our work until they do.

**Comment by nadiagorchakova** [comment] 2017-02-14 09:22
Cordaid did not renew their contract, so I'm closing this issue.

**Closed by nadiagorchakova** 2017-02-14 09:22 UTC
