### ISSUE TITLE
POST /indicator_framework/ errors

### ISSUE THREAD

**Issue by martinchristov** [akvo/akvo-rsr#3653] opened 2019-06-20 11:33 UTC
Request URL: http://localhost/rest/v1/indicator_framework/?format=json
Request Method: POST
Data:
```
{"type":"2","measure":"1","periods":[],"dimension_names":[],"result":1}
```

Response:

```
{"dimension_names":["This list may not be empty."]}
```

The dimensions (dimension_names) should not be mandatory.

**Comment by martinchristov** [comment] 2019-06-22 06:24
Please try to do a POST with the sample data:
```
dimension_names: []
measure: "1"
periods: []
result: 1
type: "2"
```

The response is:
```
AssertionError at /rest/v1/indicator_framework/
The `.create()` method does not support writable nested fields by default.
Write an explicit `.create()` method for serializer `akvo.rest.serializers.indicator.IndicatorFrameworkSerializer`, or set `read_only=True` on nested serializer fields.
```

**Comment by punchagan** [comment] 2019-06-23 11:00
Are you sure the changes are merged correctly, into your branch? I'm unable to reproduce this on `develop`.

**Closed** 2019-06-24 16:51 UTC
