### ISSUE TITLE
Clean up SPAM user accounts

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-rsr#1961] opened 2015-12-30 11:37 UTC
Currently there are many spam user accounts in the old RSR admin. It also seems that quite a lot of them are active accounts. These accounts need to be deleted. 

![screen shot 2015-12-30 at 12 34 29](https://cloud.githubusercontent.com/assets/4179989/12050207/cdad5dcc-aef1-11e5-925c-eaf99f2cfa19.png)

**Comment by KasperBrandt** [comment] 2016-05-26 10:21
Duplicate of #1753

**Closed by KasperBrandt** 2016-05-26 10:21 UTC
Labels: Chore
