### ISSUE TITLE
TypeError organisation directory

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-rsr#1538] opened 2015-05-05 05:55 UTC
Sentry reports TypeError on http://rain.akvotest.org/organisations/

Stacktrace (most recent call last):

  File "django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "akvo/rsr/views/organisation.py", line 61, in directory
    f = OrganisationFilter(qs, queryset=_organisation_directory_coll(request))
  File "akvo/rsr/views/organisation.py", line 50, in _organisation_directory_coll
    return _page_organisations(page)
  File "akvo/rsr/views/organisation.py", line 36, in _page_organisations
    return projects.all_partners().select_related(
  File "akvo/rsr/models/project.py", line 586, in all_partners
    return self._partners()
  File "akvo/rsr/models/project.py", line 568, in _partners
    orgs = orgs | project.partners

ref: http://sentry.support.akvo-ops.org/rsr/test/group/390/

**Comment by KasperBrandt** [comment] 2015-05-06 09:15
Duplicate of #1540

**Closed** 2015-05-06 09:16 UTC
